ZEN-3395 Swagger schema property with missing type not handled correctly
RepreZen/KaiZen-OpenAPI-Editor pull request #272
Opened 2017-04-04 15:15 UTC by tfesenko

* Use validation warning instead of error
* Add a quick fix for missing object type (the type is presumably object if the element has the `properties`)
<img width="379" alt="screen shot 2017-04-04 at 11 11 32 am" src="https://cloud.githubusercontent.com/assets/644582/24664083/b7e2d872-1927-11e7-8a49-583749887b4b.png">
<img width="585" alt="screen shot 2017-04-04 at 11 13 52 am" src="https://cloud.githubusercontent.com/assets/644582/24664141/dcabd258-1927-11e7-898c-f2d550263f70.png">
<img width="617" alt="screen shot 2017-04-04 at 11 13 59 am" src="https://cloud.githubusercontent.com/assets/644582/24664147/e088ffd6-1927-11e7-8258-a58be7863db4.png">

* Add validation checks for non-object types:
<img width="402" alt="screen shot 2017-04-04 at 11 11 19 am" src="https://cloud.githubusercontent.com/assets/644582/24664080/b3786ed2-1927-11e7-9653-d384e17c4b74.png">
<img width="349" alt="screen shot 2017-04-04 at 11 14 58 am" src="https://cloud.githubusercontent.com/assets/644582/24664175/f8234872-1927-11e7-8f13-8cb2043208b1.png">

2017-04-04 15:16 UTC, tfesenko commented
@andylowry , can you please review?

2017-04-08 14:03 UTC, andylowry requested changes
@tfesenko Please consider my comment re indentation

2017-04-08 14:03 UTC, andylowry commented on com.reprezen.swagedit/src/com/reprezen/swagedit/validation/QuickFixer.java
> +            return definitionIndent + "  ";
Should this be in line with YEdit's spaces-per-tab preference?

2017-04-08 14:04 UTC, andylowry commented
@tfesenko QA: I couldn't get the quick fix to show up at all. Warnings seem OK. I tested by opening the swagedit project in my workbench before launching as RCP.

2017-04-10 15:35 UTC, andylowry commented
Quick fix works. I was testing from a stale codebase.

But see related issue https://modelsolv.atlassian.net/browse/ZEN-3421

2017-04-10 18:06 UTC, tfesenko commented
@andylowry , I addressed your comment. Can you please review again?

2017-04-10 19:02 UTC, andylowry approved these changes

2017-04-10 19:02 UTC, andylowry commented
@tfesenko Looks good. Passed code review & QA. Merging

2017-04-10 19:02 UTC, merged