[#353] Validation of external $ref property values should show error …
RepreZen/KaiZen-OpenAPI-Editor pull request #358
Opened 2017-06-09 16:17 UTC by ghillairet

…on unexpected object type

Validation of reference types has been moved to ReferenceValidator that previously only validate correctness of references pointer/URIs.
It now checks the type of the reference if this one is valid, this allow to reuse the code for loading the JSON document which is referenced by it.
This validation could be slow because it will parse the referenced documents into Models.

2017-09-27 09:26 UTC, ghillairet commented
@tfesenko Can you please review. I updated this PR to include validation of types for external references. See #345 #353

2017-09-27 13:45 UTC, tfesenko commented on com.reprezen.swagedit.openapi3.tests/src/com/reprezen/swagedit/openapi3/validation/ReferenceValidatorTest.xtend
> +		assertEquals(0, errors.size())
Thanks!

2017-09-29 19:49 UTC, tfesenko commented on com.reprezen.swagedit.core/src/com/reprezen/swagedit/core/json/references/JsonDocumentManager.java
>              return getDocument(uri.toURL());
We are passing an entire URL to `JsonDocumentManager.getDocument(URL)` which includes both the `file` and `ref` parts. `JsonDocumentManager.getDocument(URL)` has a table whose keys are `URL`s in a form we are passing the here. As a result, for two different refs from the **same** external model will load the model twice. For example, for the `beamup_path_estimates_price.yaml` from the Multi-file Beamup (v3) example the `documents` map will contain a different JsonNode model for each parameter:
```
{<...>/Multi-file%20Beamup%20(v3)/models/components/beamup_parameters.yaml#/components/parameters/start_longitude={"openapi":"3.0.0", <...>}, 

<...>/Multi-file%20Beamup%20(v3)/models/components/beamup_parameters.yaml#/components/parameters/end_longitude={"openapi":"3.0.0",<...>}
}
```
But it should be a single entry for `<...>/Multi-file%20Beamup%20(v3)/models/components/beamup_parameters.yaml`! 
We should fix `JsonDocumentManager.getDocument(URL)`.

2017-09-29 19:53 UTC, tfesenko commented on com.reprezen.swagedit.core/src/com/reprezen/swagedit/core/json/references/JsonReference.java
> +    /**
Javadoc for `JsonReference.isMissing()` should be corrected:
```java
    /**
     * Returns true if the reference points to an existing JSON document and the pointer to an existing node inside that
     * document.
     * 
     * @param baseURI
     * @return true if the reference can be resolved.
     */
    public boolean isMissing(JsonDocument document, URI baseURI) {
        if (isInvalid()) {
            return false;
        }

        JsonNode resolved = resolve(document, baseURI);
        return resolved == null || resolved.isMissingNode();
    }
```
It returns true if the reference can**not** be resolved and the pointer points to an **inexistent** element.

2017-09-29 19:54 UTC, tfesenko requested changes
I left several comments including a comment about the `documents` cache.
Also, we have several test failures on this branch:
```
Failed tests: 
  CodeTemplateTextTest.test_code_template_text:148 JSON Schema validation error: 

Tests in error: 
  ValidatorTest.testValidationShouldFail_ForInvalidPointers:314 » IllegalArgument
  ValidatorTest.testValidationShouldFail_refNotJson:368 » Scanner null; mapping ...
```

2017-10-04 13:51 UTC, ghillairet commented
@tfesenko The PR has been updated.

2017-10-04 19:53 UTC, tfesenko commented
@ghillairet , I am still getting two test failures on this branch (after merge master in to the task branch, the master is green):
```
Failed tests: 
  ValidatorTest.testValidationShouldFail_ForInvalidPointers:317 expected:<1> but was:<2>
  ValidatorTest.testValidationShouldFail_refNotJson:371 expected:<1> but was:<2>

```

2017-10-04 20:54 UTC, tfesenko commented
Passed code review and QA.
All OK except for test failures.

2017-10-05 10:24 UTC, ghillairet commented
Tests have been fixed.

2017-10-05 17:57 UTC, tfesenko commented on com.reprezen.swagedit.openapi3.tests/src/com/reprezen/swagedit/openapi3/validation/ValidatorTest.xtend
> +			      type: object
:smile:

2017-10-05 18:21 UTC, tfesenko commented
Looks good. Thanks!!

2017-10-05 18:21 UTC, merged