ZEN-4367 - Resource templates don't populate schema reference correctly (DO NOT MERGE)
RepreZen/KaiZen-OpenAPI-Editor pull request #473
Opened 2018-09-02 16:49 UTC by tfesenko

Bug: stray quote in 2nd variable occurrence - If we leave the quotes in, we see this bug. It may be a KZOE bug, in which case we should aim to fix it.
Bug: code assist prepends reference to selected text instead of replacing it. We only see this bug when we do not surround the template variable with quotes.

2018-09-11 21:59 UTC, tfesenko commented
@ghillairet , this PR is ready for your review

2018-09-12 14:20 UTC, ghillairet commented on com.reprezen.swagedit.openapi3.tests/src/com/reprezen/swagedit/openapi3/assist/JsonReferenceProposalProvider_Quotes_Test.xtend
> +	/*============    Code below copied from utils.Cursors, otherwise Xtend won't compile     ============= */
@tfesenko Any clue why it does not compile for you? I have it working.

2018-09-12 14:27 UTC, ghillairet requested changes
@tfesenko Looks good. It works as expected, although I would prefer we remove the duplicate in the tests.

2018-09-18 15:51 UTC, tfesenko commented
> although I would prefer we remove the duplicate in the tests.

Covered by https://modelsolv.atlassian.net/browse/ZEN-4428, will be fixed later.

Merging.

2018-09-18 15:51 UTC, merged